#!/bin/bash

# PW - simple password user account storage management based on CSV.

# Copyright (c) 2016 Digidog (aka. diqidoq) - Released under GPL v3
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

DataTable(){
cat << EOF
--------------
| Full Table |
--------------
| 1   | 2    | 3   | 4    | 5    | 6    | 7  | 8   | 9 | 10    | 11 | 12   | 13   | 14    | 15   | 16  | 17 | 18 | 19  |
|-----|------|-----|------|------|------|----|-----|---|-------|----|------|------|-------|------|-----|----|----|-----|
| cat | type | srv | http | nick | name | id | crn | @ | login | pw | note | addr | btown | bday | age | Q  | A  | use |
EOF
}

Help(){
cat << EOF

Type pw <username> or pw <service> <username> or any other combination (e.g. pw <real neme> <cat>) to filter output.
				
Standart Output: 
--------------------------------------------------------
type c2 | service c3| uname c5 | email c9 | password c11
--------------------------------------------------------

EOF

DataTable

cat << EOF

[!] For input you can use both directives (nr or label) to target the input column.
[!] cat stands for categories. you can choose your own tags or a team based tag system for later filtering

-i = input by simple form fields asking you: column=value column=value
-a = add a row of raw csv line, e.g.: cat;type;srv;-;yournick;-;-;-;your@mail.de;loginname;pass;-;-;-;-;-;-;-;- 

EOF
	}

if [[ "$@" ]] ; then

FILENAME=pw.csv
PWPATH=/media/digidog/portable/BFK/s/U/ts/pcuserdata/Documents/Registries_Logins/$FILENAME

case $1 in
	-h|--help)
		Help		
		exit 1
	;;
	-i|--input)
		# we try to pipe the input into our pw.csv
		# we need to check if the count of 19 columns is given to keep the db consistent
		unset ROW
		declare -a ROW
		i=0
		read -p "Categorie tags with comma: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Type of Service: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Service Name: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Link to the Login: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Nickname/Username: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Real Name: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "ID in your unique Persona system: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Customer Reference Number, if any: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Email Adress for Login: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Login name or Login type (user-login/mail-login): " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Password: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Additional notes/(info to the account: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Address if divergent from unique Person of account: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Birth town if divergent from unique Person of account: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Birthday if divergent from unique Person of account: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Age if divergent from unique Person of account: " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Challenge questions (watch order): " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Challenge responses (same order): " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi ; ((i++))
		read -p "Usage info (like notes, but more specific to history): " ROW[$i] ; if [ -z "${ROW[$i]}" ] ; then ROW[$i]="-" ; fi
		
		IFS=';' ; ROWSET="${ROW[*]}" ; IFS=$' \t\n'
		
		DataTable
		
		echo "$ROWSET"
		echo "-------"
		read -p "Please check the entry fo possible errors. Does it look ok (y), or do we need ot break up (n)? <y/n>: " ynROW
		
		if [ "$ynROW" == "n" ] || [ -z "$ynROW" ] ; then
		  Help
		  exit 1
		else
		  echo "$ROWSET" >> $PWPATH 
		fi
	;;

			# -a|--add)
			# 	shift
			#	echo "$@" >> $PWPATH
			#	exit
			#	;;
	*)
		if [[ "$2" ]] ; then
		 grep --color -i $1 $PWPATH | grep --color -i $2 | cut -d ';' -f2,3,5,9,10,11,12 | column -ts ';'
		else
		 grep --color -i $1 $PWPATH | cut -d ';' -f2,3,5,9,10,11,12 | column -ts ';'
		fi
	;;
esac

else
	echo "
	PW - simple password user account storage management based on CSV.
	Type -h or --help for help and options.
	"
fi

exit 0

# for index in "${!array[@]}"
# do
#  echo "$index ${array[index]}"
# done
